run_cmd: "claude -p ${prompt}"

runtime_env_config:
  type: node
  custom_install_cmd: "npm install -g @anthropic-ai/claude-code"

env:
  ANTHROPIC_BASE_URL: "" # Enter your anthropic base url
  ANTHROPIC_AUTH_TOKEN: "" # Enter your anthropic auth token
  ANTHROPIC_API_KEY: "" # Keep this empty