proxy_rules:
  qwen: "https://offline-whale-wave.alibaba-inc.com/api/v2/services/aigc/text-generation/v1/chat/completions"
  gpt: "https://api.openai.com/v1/chat/completions"
retryable_status_codes:
  - 409, # ENGINE_CONCURRENCY_CONFLICT
  - 429, # THROTTLING
  - 499, # CLIENT_DISCONNECT
  - 518, # ROUTE_CONFIG_ERROR
  - 519, # NETTY_CATCH_ERROR
  - 520, # PYRTP_CONNECT_ERROR
  - 523, # READ_TIME_OUT
  - 524, # RETRY_EXHAUSTED
  - 527, # CONNECTION_RESET_EXCEPTION
  - 528, # ENGINE_RESPONSE_TOO_LARGE
  - 600, # BALANCING_WORKER_EXCEPTION
  - 602, # MALLOC_EXCEPTION
  - 603, # ENGINE_TIMEOUT_EXCEPTION
  - 8000, # ENGINE_ABNORMAL_DISCONNECT_EXCEPTION
  - 8200, # GET_HOST_FAILED
  - 8202, # CONNECT_FAILED
  - 8211, # DECODE_MALLOC_FAILED
  - 8213, # WAIT_TO_RUN_TIMEOUT
  - 8303  # CACHE_STORE_LOAD_SEND_REQUEST_FAILED
timeout: 180  