run_cmd: "iflow -p ${prompt} --yolo"

runtime_env_config:
  type: node
  npm_registry: "https://registry.npmmirror.com"
  custom_install_cmd: "npm i -g @iflow-ai/iflow-cli@latest"

env:
  IFLOW_API_KEY: "xxxx" # Not important, just a placeholder
  IFLOW_BASE_URL: "http://localhost:8080/v1" # Enter your base url
  IFLOW_MODEL_NAME: "" # Enter your model name 

model_service_config:
  enabled: true
  type: local
